apiVersion: v1
kind: Service
metadata:
  name: msone-service
  namespace: default
spec: 
  type: NodePort
  ports:
    - targetPort: 3000
      port: 80
      nodePort: 30009
  selector:
    app: micro-service-one
